version: '3.8'

services:
  minecraft-skybees:
    build: .
    container_name: skybees-server
    # Redémarrage automatique sauf si arrêté manuellement
    restart: unless-stopped
    ports:
      # Port du serveur Minecraft
      - "25565:25565"
    volumes:
      # Persister les données du monde
      - ./world:/minecraft/world
      - ./logs:/minecraft/logs
      - ./config:/minecraft/config
      - ./server.properties:/minecraft/server.properties
      - ./ops.json:/minecraft/ops.json
      - ./whitelist.json:/minecraft/whitelist.json
      - ./banned-ips.json:/minecraft/banned-ips.json
      - ./banned-players.json:/minecraft/banned-players.json
    environment:
      # Configuration de la mémoire (modifiable ici)
      - MEMORY_MIN=4096M
      - MEMORY_MAX=5120M
    stdin_open: true
    tty: true
    # Limites de ressources pour éviter la surcharge
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
