events.listen('item.registry', event => {


  event.create('salad').food(food => {food.hunger(9).saturation(1)}).displayName('Salad').maxStackSize(64)
  event.create('valdanium_ingot').displayName('Valdanium Ingot')
  event.create('valdanium_nugget').displayName('Valdanium Nugget')
  event.create('double_arrow').displayName('Green Double Arrow')
  event.create('wooden_double_arrow').displayName('Wodden Double Arrow')
  event.create('double_arrow_cast').displayName('Double Arrow Gold Cast')
  event.create('large_plate_diamond').displayName('Diamond Large Plate')
  event.create('large_plate_netherite').displayName('Netherite Large Plate')
  event.create('bee').displayName('Bee')
  event.create('rgb_dye').displayName('RGB Dye')
  //dna
  event.create('cobblestone_bee_dna').displayName('Cobblestone Bee DNA')
  event.create('andesite_bee_dna').displayName('Andesite Bee DNA')
  event.create('diorite_bee_dna').displayName('Diorite Bee DNA')
  event.create('dirt_bee_dna').displayName('Dirt Bee DNA')
  event.create('granite_bee_dna').displayName('Granite Bee DNA')
  event.create('gravel_bee_dna').displayName('Gravel Bee DNA')
  event.create('lava_bee_dna').displayName('Lava Bee DNA')
  event.create('rgbee_bee_dna').displayName('Rgbee Bee DNA')
  event.create('sand_bee_dna').displayName('Sand Bee DNA')
  event.create('snowball_bee_dna').displayName('Snowball Bee DNA')
  event.create('water_bee_dna').displayName('Water Bee DNA')
  event.create('wood_bee_dna').displayName('Wood Bee DNA')
  event.create('basalz_dna').displayName('Basalz DNA')
  event.create('bee_dna').displayName('Bee DNA')
  event.create('blaze_dna').displayName('Blaze DNA')
  event.create('blitz_dna').displayName('Blitz DNA')
  event.create('blizz_dna').displayName('Blizz DNA')
  event.create('empty_dna').displayName('Empty DNA')
  event.create('enderman_dna').displayName('Enderman DNA')
  event.create('shulker_dna').displayName('Shulker DNA')
  event.create('guardian_dna').displayName('Guardian DNA')
  //dna_creator
  event.create('fishi_bee_dna').displayName('Fishi Bee DNA')
  event.create('matter_bee_dna').displayName('Matter Bee DNA')

})
