events.listen('block.registry', event => {


  //Nectarblock
  //tier1
event.create('nectarblock_clay').displayName('Clay Bee Nectarblock')
event.create('nectarblock_coal').displayName('Coal Bee Nectarblock')
event.create('nectarblock_fluorite').displayName('Fluorite Bee Nectarblock')
event.create('nectarblock_ice').displayName('Icy Bee Nectarblock')
event.create('nectarblock_iron').displayName('Iron Bee Nectarblock')
event.create('nectarblock_lead').displayName('Lead Bee Nectarblock')
event.create('nectarblock_marble').displayName('Marble Bee Nectarblock')
event.create('nectarblock_niter').displayName('Niter Bee Nectarblock')
event.create('nectarblock_obsidian').displayName('Obsidian Bee Nectarblock')
event.create('nectarblock_prismarine').displayName('Prismarine Bee Nectarblock')
event.create('nectarblock_rubber').displayName('Rubber Bee Nectarblock')
event.create('nectarblock_salt').displayName('Salt Bee Nectarblock')
event.create('nectarblock_sea').displayName('Sea Bee Nectarblock')
event.create('nectarblock_slime').displayName('Slimy Bee Nectarblock')
event.create('nectarblock_tin').displayName('Tin Bee Nectarblock')
//tier2
event.create('nectarblock_apatite').displayName('Apatite Bee Nectarblock')
event.create('nectarblock_astral').displayName('Astral Bee Nectarblock')
event.create('nectarblock_bituminous_sand').displayName('Bituminous Sand Bee Nectarblock')
event.create('nectarblock_black_iron').displayName('Black Iron Bee Nectarblock')
event.create('nectarblock_compressed_iron').displayName('Compressed Iron Bee Nectarblock')
event.create('nectarblock_creeper').displayName('Creeper Bee Nectarblock')
event.create('nectarblock_dielectric_paste').displayName('Dielectric Paste Bee Nectarblock')
event.create('nectarblock_manasteel').displayName('Manasteel Bee Nectarblock')
event.create('nectarblock_nether').displayName('Nether Bee Nectarblock')
event.create('nectarblock_nickel').displayName('Nickel Bee Nectarblock')
event.create('nectarblock_seared').displayName('Seared Bee Nectarblock')
event.create('nectarblock_silver').displayName('Silver Bee Nectarblock')
event.create('nectarblock_skeleton').displayName('Skeleton Bee Nectarblock')
event.create('nectarblock_steel').displayName('Steel Bee Nectarblock')
event.create('nectarblock_zombie').displayName('Zombie Bee Nectarblock')
//tier3
event.create('nectarblock_ancient').displayName('Ancient Bee Nectarblock')
event.create('nectarblock_copper').displayName('Copper Bee Nectarblock')
event.create('nectarblock_elementium').displayName('Elementium Bee Nectarblock')
event.create('nectarblock_ender').displayName('Ender Bee Nectarblock')
event.create('nectarblock_invar').displayName('Invar Bee Nectarblock')
event.create('nectarblock_quartz').displayName('Nether Quartz Bee Nectarblock')
event.create('nectarblock_osmium').displayName('Osmium Bee Nectarblock')
event.create('nectarblock_radioactive').displayName('Radioactive Bee Nectarblock')
event.create('nectarblock_sheep').displayName('Sheep Bee Nectarblock')
event.create('nectarblock_slimesteel').displayName('Slimesteel Bee Nectarblock')
event.create('nectarblock_sulfur').displayName('Sulfur Bee Nectarblock')
event.create('nectarblock_wither_skeleton').displayName('Wither Skeleton Bee Nectarblock')
//tier4
event.create('nectarblock_bronze').displayName('Bronze Bee Nectarblock')
event.create('nectarblock_certus').displayName('Certus Bee Nectarblock')
event.create('nectarblock_cobalt').displayName('Cobalt Bee Nectarblock')
event.create('nectarblock_constantan').displayName('Constantan Bee Nectarblock')
event.create('nectarblock_gold').displayName('Gold Bee Nectarblock')
event.create('nectarblock_lithium').displayName('Lithium Bee Nectarblock')
event.create('nectarblock_refined_obsidian').displayName('Refined Obsidian Bee Nectarblock')
event.create('nectarblock_wither').displayName('Wither Bee Nectarblock')
//tier5
event.create('nectarblock_cinnabar').displayName('Cinnabar Bee Nectarblock')
event.create('nectarblock_electrum').displayName('Electrum Bee Nectarblock')
event.create('nectarblock_fluix').displayName('Fluix Bee Nectarblock')
event.create('nectarblock_hepatizon').displayName('Hepatizon Bee Nectarblock')
event.create('nectarblock_manyullyn').displayName('Manyullyn Bee Nectarblock')
event.create('nectarblock_pigman').displayName('Pigman Bee Nectarblock')
event.create('nectarblock_queens_slime').displayName('Queens Slime Bee Nectarblock')
event.create('nectarblock_rose_gold').displayName('Rose Gold Bee Nectarblock')
event.create('nectarblock_silicon').displayName('Silicon Bee Nectarblock')
//tier6
event.create('nectarblock_basalz').displayName('Basalz Bee Nectarblock')
event.create('nectarblock_blitz').displayName('Blitz Bee Nectarblock')
event.create('nectarblock_blizz').displayName('Blizz Bee Nectarblock')
event.create('nectarblock_end').displayName('End Bee Nectarblock')
event.create('nectarblock_lapis').displayName('Lapis Bee Nectarblock')
event.create('nectarblock_lumium').displayName('Lumium Bee Nectarblock')
event.create('nectarblock_pig_iron').displayName('Pig Iron Bee Nectarblock')
event.create('nectarblock_redstone').displayName('Redstone Bee Nectarblock')
event.create('nectarblock_refined_glowstone').displayName('Refined Glowstone Bee Nectarblock')
//tier7
event.create('nectarblock_blaze').displayName('Blaze Bee Nectarblock')
event.create('nectarblock_chorus').displayName('Chorus Bee Nectarblock')
event.create('nectarblock_dragon').displayName('Dragon Bee Nectarblock')
event.create('nectarblock_flux').displayName('Flux Bee Nectarblock')
event.create('nectarblock_signalum').displayName('Signalum Bee Nectarblock')
//tier8
event.create('nectarblock_diamond').displayName('Diamond Bee Nectarblock')
//tier9
event.create('nectarblock_emerald').displayName('Emerald Bee Nectarblock')
event.create('nectarblock_enderium').displayName('Enderium Bee Nectarblock')
event.create('nectarblock_terrasteel').displayName('Terrasteel Bee Nectarblock')
event.create('nectarblock_draconium').displayName('Draconium Bee Nectarblock')
event.create('nectarblock_awakened_draconium').displayName('Awakened Draconium Bee Nectarblock')
event.create('nectarblock_chaos').displayName('Chaos Bee Nectarblock')



  })
