
#General settings
[general]
	#Use config instead of datapack
	use_config = true

	#List settings
	#Syntax: ["modid:block|weight"]
	#Example: ["minecraft:stone|2","minecraft:dirt|1"]
	#Forge tags are supported
	[general.lists]
		#Basalt gen
		block_list_basalt = ["minecraft:basalt|60", "minecraft:blackstone|60", "minecraft:netherrack|60"]
		#Cobble gen
		block_list_cobble = ["minecraft:cobblestone|60", "minecraft:stone|20"]
		#Stone gen
		block_list_stone = ["minecraft:stone|30", "minecraft:granite|10", "minecraft:diorite|10", "minecraft:andesite|10"]

		#Custom settings
		[general.lists.custom]
			#Custom generators
			#Syntax: [gen]
			#Gen: [type, block, list]
			#Type: cobblestone, stone
			#Block: resource location of the block below the generated block
			#List: see List settings
			#Examples:
			#custom_generators = [
			#   ["cobblestone", "minecraft:diamond_block", ["minecraft:diamond_block"]],
			#   ["cobblestone", "minecraft:dirt", ["forge:dirt"]],
			#   ["cobblestone", "minecraft:white_wool", ["minecraft:wool"]]]
			custom_generators = [["cobblestone", "compressium:cobblestone_3", ["minecraft:stone|60", "kubejs:seed_ore|40"]], ["cobblestone", "minecraft:sandstone", ["minecraft:sand|35", "minecraft:red_sand|25", "thermal:oil_sand|10", "thermal:oil_red_sand|10", "astralsorcery:aquamarine_sand_ore|10", "mekanism:block_salt|10"]]]

