
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 8411814
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "metallic"
	#Should items of this material have the enchanted glow.
	hasEffect = false

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

[mekanism]
	#The base to use in Mekanism's Combiner to recreate ores.
	ore_base = "#forge:cobblestone"

[exnihilosequentia]
	#Should gravel sieve recipes be added.
	sieveGravel = true
	#Should crushed netherrack sieve recipes be added.
	sieveCrushedNetherrack = false
	#Should crushed end stone sieve recipes be added.
	sieveCrushedEndstone = false

