craftingTable.removeRecipe(<item:resourcefulbees:t1_beehive>);
craftingTable.removeRecipe(<item:resourcefulbees:t2_beehive>);
craftingTable.removeRecipe(<item:resourcefulbees:t3_beehive>);
craftingTable.removeRecipe(<item:resourcefulbees:t4_beehive>);
craftingTable.removeRecipe(<item:resourcefulbees:t1_apiary>);
craftingTable.removeRecipe(<item:resourcefulbees:centrifuge>);
craftingTable.removeRecipe(<item:resourcefulbees:waxed_machine_block>);
craftingTable.removeRecipe(<item:resourcefulbees:centrifuge_casing>);
craftingTable.removeRecipe(<item:resourcefulbees:elite_centrifuge_casing>);
